### PR TITLE
Fix relative links in README tab to point to GitHub

### LINKED ISSUE #115: Relative links in README tab resolve to gittensor.io instead of GitHub
## Description

Relative links rendered in the README tab on the repository page incorrectly resolve to localhost paths instead of pointing to the corresponding GitHub URLs.

## Steps to Reproduce

1. Open `https://gittensor.io/miners/repository?name=bitcoin%2Fbitcoin`
2. Navigate to the **Readme** tab
3. Click on any relative link in the rendered README (e.g. `CONTRIBUTING.md`, `doc/developer-notes.md`, or `doc`)

## Expected Behavior

Relative links should resolve to the source GitHub repository:

- `CONTRIBUTING.md` → `https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md`
- `doc/developer-notes.md` → `https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md`
- `doc` → `https://github.com/bitcoin/bitcoin/blob/master/doc`

## Actual Behavior

Relative links resolve to gittensor.io paths:

- `CONTRIBUTING.md` → `https://gittensor.io/miners/CONTRIBUTING.md`
- `doc/developer-notes.md` → `https://gittensor.io/miners/doc/developer-notes.md`
- `doc` → `https://gittensor.io/doc`

## Environment

- Browser: Chrome
- OS: Linux

## Additional Context

This affects all relative links in README content. Absolute links (`https://...`) and anchor links (`#...`) are unaffected. The fix should rewrite relative hrefs to prefix them with the GitHub blob URL for the repository.

https://github.com/user-attachments/assets/31290032-7d26-4ff4-87ff-799efe933dd8

This also happens in `Contributing` tab.

### PR DESCRIPTION
**Pull request by tmimmanuel**
## Summary

Rewrite relative links in rendered README markdown to resolve to the source GitHub repository instead of localhost. Relative hrefs (e.g. `CONTRIBUTING.md`, `doc/developer-notes.md`, `doc`) are prefixed with the correct GitHub blob URL.

## Related Issues

Fixes #115

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Other (describe below)

## Checklist

- [ ] New components are modularized/separated where sensible
- [ ] Uses predefined theme (e.g. no hardcoded colors)
- [x] Responsive/mobile checked
- [x] Tested against the test API
- [x] `npm run format` and `npm run lint:fix` have been run
- [x] `npm run build` passes
- [x] Screenshots included for any UI/visual changes

## Screenshots
[Screencast from 2026-03-20 20-06-08.webm](https://github.com/user-attachments/assets/50f8c5bf-99ef-4d97-a413-b3498188d9c6)

### CODE REVIEW

File: src/components/repositories/ContributingViewer.tsx [hunk 1]
```diff
@@ -81,6 +81,37 @@ const ContributingViewer: React.FC<ContributingViewerProps> = ({
     );
   }
 
+  // Custom renderer for links to handle relative paths
+  const LinkRenderer = (props: any) => {
```
Comment (anderdc) [inline src/components/repositories/ContributingViewer.tsx]: It looks like we can abstract this out to its own file since we define it the exact same in two different places

**Review by anderdc — CHANGES_REQUESTED** [review]

**Comment by anderdc** [comment]
We need to still add `MarkdownRenderer.tsx` to the `src/components/repositories/index.ts` file

**Comment by anderdc** [comment]
please fix CI

**Comment by tmimmanuel** [comment]
@anderdc  I fixed the errors, plz review.

**Comment by anderdc** [comment]
hmm I like how this solves a real problem, but I feel like it can be done simpler

**Comment by tmimmanuel** [comment]
I replaced two factory functions (`createLinkRenderer`, `createImageRenderer`) with a single `resolveRelativeUrl` helper that just resolves URLs
Please review. @anderdc

**Comment by anderdc** [comment]
failing format

**Comment by tmimmanuel** [comment]
@anderdc 
fixed merge conflicts, lint errors, please review.

**Comment by tmimmanuel** [comment]
@anderdc could you please review my PR?

**Review by anderdc — APPROVED** [review]
